/*
 * File:           C:\Users\Jeroen\OneDrive\DIY\Elektronica\DSPPreamp\software\firmware\sigma\DSPPreamp_IC_1_PARAM.h
 *
 * Created:        Wednesday, September 2, 2020 9:07:36 PM
 * Description:    DSPPreamp:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2020 Analog Devices, Inc. All rights reserved.
 */
#ifndef __DSPPREAMP_IC_1_PARAM_H__
#define __DSPPREAMP_IC_1_PARAM_H__


/* Module Gain2 - Gain*/
#define MOD_GAIN2_COUNT                                1
#define MOD_GAIN2_DEVICE                               "IC1"
#define MOD_GAIN2_GAIN1940ALGNS2_ADDR                  0
#define MOD_GAIN2_GAIN1940ALGNS2_FIXPT                 0x00800000
#define MOD_GAIN2_GAIN1940ALGNS2_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN2_GAIN1940ALGNS2_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Gain1 - Gain*/
#define MOD_GAIN1_COUNT                                1
#define MOD_GAIN1_DEVICE                               "IC1"
#define MOD_GAIN1_GAIN1940ALGNS1_ADDR                  1
#define MOD_GAIN1_GAIN1940ALGNS1_FIXPT                 0x00800000
#define MOD_GAIN1_GAIN1940ALGNS1_VALUE                 SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_GAIN1_GAIN1940ALGNS1_TYPE                  SIGMASTUDIOTYPE_FIXPOINT

/* Module Nx1-1 - Mono Switch Nx1*/
#define MOD_NX1_1_COUNT                                2
#define MOD_NX1_1_DEVICE                               "IC1"
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR    2
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT   0x00800000
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_NX1_1_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR    3
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT   0x00000000
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_NX1_1_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv1 - Running Average*/
#define MOD_AVGENV1_COUNT                              3
#define MOD_AVGENV1_DEVICE                             "IC1"
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_ADDR  4
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_FIXPT 0x000012DE
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000575811989360853)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_ADDR 5
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_FIXPT 0x00000000
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_ADDR 6
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_FIXPT 0x00000012
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.17013888888889E-06)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module NFilter1 - Nth Order Filter*/
#define MOD_PREGAIN_NFILTER1_COUNT                     5
#define MOD_PREGAIN_NFILTER1_DEVICE                    "IC1"
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_0B_1_ADDR 7
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_0B_1_FIXPT 0x007F0E41
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_0B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.992622542756119)
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_0B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1B_1_ADDR 8
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1B_1_FIXPT 0xFF01E37E
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98524508551224)
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2B_1_ADDR 9
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2B_1_FIXPT 0x007F0E41
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.992622542756119)
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1A_1_ADDR 10
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1A_1_FIXPT 0x00FE1ABA
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1A_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98519065789626)
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_1A_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2A_1_ADDR 11
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2A_1_FIXPT 0xFF81E1B5
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2A_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.985299513128214)
#define MOD_PREGAIN_NFILTER1_ALG0_STAGE1_NTHORDERDOUBLE1_2A_1_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter1 - General (2nd order)*/
#define MOD_PREGAIN_GENFILTER1_COUNT                   5
#define MOD_PREGAIN_GENFILTER1_DEVICE                  "IC1"
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B0_ADDR     12
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B0_FIXPT    0x00800000
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B0_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B0_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B1_ADDR     13
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B1_FIXPT    0x00000000
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B1_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B1_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B2_ADDR     14
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B2_FIXPT    0x00000000
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B2_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_B2_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A0_ADDR     15
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A0_FIXPT    0x00000000
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A0_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A0_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A1_ADDR     16
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A1_FIXPT    0x00000000
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A1_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PREGAIN_GENFILTER1_ALG0_STAGE0_A1_TYPE     SIGMASTUDIOTYPE_FIXPOINT

/* Module PREGAIN_BYPASS - Mono Switch Nx1*/
#define MOD_PREGAIN_PREGAIN_BYPASS_COUNT               2
#define MOD_PREGAIN_PREGAIN_BYPASS_DEVICE              "IC1"
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 17
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 18
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_PREGAIN_PREGAIN_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module GAIN1 - Gain*/
#define MOD_DSPDISTORTION_GAIN1_COUNT                  1
#define MOD_DSPDISTORTION_GAIN1_DEVICE                 "IC1"
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_ADDR    19
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_FIXPT   0x00B4CE07
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.41253754462275)
#define MOD_DSPDISTORTION_GAIN1_GAIN1940ALGNS3_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module GAIN2 - Gain*/
#define MOD_DSPDISTORTION_GAIN2_COUNT                  1
#define MOD_DSPDISTORTION_GAIN2_DEVICE                 "IC1"
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_ADDR    20
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_FIXPT   0x02818508
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(5.01187233627272)
#define MOD_DSPDISTORTION_GAIN2_GAIN1940ALGNS5_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module SoftClip1 - Standard Cubic*/
#define MOD_DSPDISTORTION_SOFTCLIP1_COUNT              4
#define MOD_DSPDISTORTION_SOFTCLIP1_DEVICE             "IC1"
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_ADDR 21
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_FIXPT 0x00266666
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.3)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHA_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_ADDR 22
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_FIXPT 0x01AAAAAA
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(3.33333333333333)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ALPHAM1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_ADDR 23
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_FIXPT 0x002AAAAA
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.333333333333333)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21ONETHIRD_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_ADDR 24
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_FIXPT 0x00555555
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.666666666666667)
#define MOD_DSPDISTORTION_SOFTCLIP1_ALG0_SOFTCLIPALGG21TWOTHIRD_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module VOLUME - Single Volume*/
#define MOD_DSPDISTORTION_VOLUME_COUNT                 1
#define MOD_DSPDISTORTION_VOLUME_DEVICE                "IC1"
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_ADDR   25
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_FIXPT  0x00800000
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_DSPDISTORTION_VOLUME_GAIN1940ALGNS4_TYPE   SIGMASTUDIOTYPE_FIXPOINT

/* Module BYPASS - Mono Switch Nx1*/
#define MOD_DSPDISTORTION_BYPASS_COUNT                 1
#define MOD_DSPDISTORTION_BYPASS_DEVICE                "IC1"
#define MOD_DSPDISTORTION_BYPASS_MONOSWSLEW_ADDR       26
#define MOD_DSPDISTORTION_BYPASS_MONOSWSLEW_FIXPT      0x00000001
#define MOD_DSPDISTORTION_BYPASS_MONOSWSLEW_VALUE      SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_DSPDISTORTION_BYPASS_MONOSWSLEW_TYPE       SIGMASTUDIOTYPE_INTEGER

/* Module SW vol 1 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL1_COUNT                               2
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_ALG0_TARGET_ADDR                    27
#define MOD_SWVOL1_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL1_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL1_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL1_ALG0_STEP_ADDR                      28
#define MOD_SWVOL1_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL1_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL1_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

/* Module ANALOG_BYPASS - Mono Switch Nx1*/
#define MOD_ANALOG_BYPASS_COUNT                        1
#define MOD_ANALOG_BYPASS_DEVICE                       "IC1"
#define MOD_ANALOG_BYPASS_MONOSWSLEW_ADDR              29
#define MOD_ANALOG_BYPASS_MONOSWSLEW_FIXPT             0x00000001
#define MOD_ANALOG_BYPASS_MONOSWSLEW_VALUE             SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_ANALOG_BYPASS_MONOSWSLEW_TYPE              SIGMASTUDIOTYPE_INTEGER

/* Module NFilter1_2 - Nth Order Filter*/
#define MOD_POSTGAIN_NFILTER1_2_COUNT                  5
#define MOD_POSTGAIN_NFILTER1_2_DEVICE                 "IC1"
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_0B_1_ADDR 30
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_0B_1_FIXPT 0x00800000
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_0B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_0B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1B_1_ADDR 31
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1B_1_FIXPT 0x00000000
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2B_1_ADDR 32
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2B_1_FIXPT 0x00000000
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1A_1_ADDR 33
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1A_1_FIXPT 0x00000000
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1A_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_1A_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2A_1_ADDR 34
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2A_1_FIXPT 0x00000000
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2A_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_POSTGAIN_NFILTER1_2_ALG0_STAGE1_NTHORDERDOUBLE2_2A_1_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Gen Filter2 - General (2nd order)*/
#define MOD_POSTGAIN_GENFILTER2_COUNT                  5
#define MOD_POSTGAIN_GENFILTER2_DEVICE                 "IC1"
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B0_ADDR    35
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B0_FIXPT   0x007F563F
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B0_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994819572508497)
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B0_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B1_ADDR    36
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B1_FIXPT   0xFF015382
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B1_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.98963914501699)
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B1_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B2_ADDR    37
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B2_FIXPT   0x007F563F
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B2_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.994819572508497)
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_B2_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A1_ADDR    38
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A1_FIXPT   0x00FEAC0D
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A1_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.98962569173299)
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A1_TYPE    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A2_ADDR    39
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A2_FIXPT   0xFF815311
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A2_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.989652598300996)
#define MOD_POSTGAIN_GENFILTER2_ALG0_STAGE0_A2_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_LOW - Medium Size Eq*/
#define MOD_POSTGAIN_PO_LOW_COUNT                      5
#define MOD_POSTGAIN_PO_LOW_DEVICE                     "IC1"
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B0_ADDR        40
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B0_FIXPT       0x00B57FF0
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B0_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.41796692889598)
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B0_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B1_ADDR        41
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B1_FIXPT       0xFEA325CF
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B1_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-2.72540869460482)
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B1_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B2_ADDR        42
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B2_FIXPT       0x00A7E233
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B2_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.31159061627524)
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_B2_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A1_ADDR        43
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A1_FIXPT       0x00F700F3
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A1_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.92971646954865)
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A1_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A2_ADDR        44
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A2_FIXPT       0xFF88B0D2
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A2_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.932103883858596)
#define MOD_POSTGAIN_PO_LOW_ALG0_STAGE0_A2_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module Mid EQ1 - Medium Size Eq*/
#define MOD_POSTGAIN_MIDEQ1_COUNT                      5
#define MOD_POSTGAIN_MIDEQ1_DEVICE                     "IC1"
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B0_ADDR        45
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B0_FIXPT       0x007DB95E
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B0_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.982219483922217)
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B0_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B1_ADDR        46
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B1_FIXPT       0xFF0976B1
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B1_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.92606542854614)
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B1_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B2_ADDR        47
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B2_FIXPT       0x0079268E
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B2_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.946489172806522)
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_B2_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A0_ADDR        48
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A0_FIXPT       0x00F6894F
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A0_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.92606542854614)
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A0_TYPE        SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A1_ADDR        49
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A1_FIXPT       0xFF892014
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A1_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.92870865672874)
#define MOD_POSTGAIN_MIDEQ1_ALG0_STAGE0_A1_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module Mid EQ1_2 - Medium Size Eq*/
#define MOD_POSTGAIN_MIDEQ1_2_COUNT                    5
#define MOD_POSTGAIN_MIDEQ1_2_DEVICE                   "IC1"
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B0_ADDR      50
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B0_FIXPT     0x007EF2AA
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B0_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.991780571848763)
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B0_TYPE      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B1_ADDR      51
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B1_FIXPT     0xFF07F9EC
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B1_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.93768552201106)
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B1_TYPE      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B2_ADDR      52
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B2_FIXPT     0x00796A8C
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B2_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.948564125133659)
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_B2_TYPE      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A0_ADDR      53
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A0_FIXPT     0x00F80614
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A0_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.93768552201106)
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A0_TYPE      SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A1_ADDR      54
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A1_FIXPT     0xFF87A2C9
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A1_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.940344696982422)
#define MOD_POSTGAIN_MIDEQ1_2_ALG0_STAGE0_A1_TYPE      SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_HIGH - Medium Size Eq*/
#define MOD_POSTGAIN_PO_HIGH_COUNT                     5
#define MOD_POSTGAIN_PO_HIGH_DEVICE                    "IC1"
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B0_ADDR       55
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B0_FIXPT      0x00EB9A70
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B0_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.84065058734194)
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B0_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B1_ADDR       56
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B1_FIXPT      0xFE37C2F5
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-3.56436293012797)
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B1_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B2_ADDR       57
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B2_FIXPT      0x00DD18A2
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.72731428529799)
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_B2_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A1_ADDR       58
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A1_FIXPT      0x00F4E867
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.91334243485499)
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A1_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A2_ADDR       59
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A2_FIXPT      0xFF8AA192
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.91694437736695)
#define MOD_POSTGAIN_PO_HIGH_ALG0_STAGE0_A2_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_TONECONTROL - General (2nd order)*/
#define MOD_POSTGAIN_PO_TONECONTROL_COUNT              5
#define MOD_POSTGAIN_PO_TONECONTROL_DEVICE             "IC1"
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_ADDR 60
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_FIXPT 0xFF55F870
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.32835584719983)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B0_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_ADDR 61
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_FIXPT 0x01564E55
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.67426555857715)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_ADDR 62
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_FIXPT 0xFF5425B2
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.34259972408618)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_B2_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_ADDR 63
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_FIXPT 0x00F1FECC
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.89058836810461)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_ADDR 64
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_FIXPT 0xFF8DA089
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.893538397383039)
#define MOD_POSTGAIN_PO_TONECONTROL_ALG0_STAGE0_A2_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_PRESENCE - Nth Order Filter*/
#define MOD_POSTGAIN_PO_PRESENCE_COUNT                 5
#define MOD_POSTGAIN_PO_PRESENCE_DEVICE                "IC1"
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_0B_1_ADDR 65
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_0B_1_FIXPT 0x0007BE6A
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_0B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0604985076309406)
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_0B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1B_1_ADDR 66
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1B_1_FIXPT 0x000F7CD4
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.120997015261881)
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2B_1_ADDR 67
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2B_1_FIXPT 0x0007BE6A
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2B_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0604985076309406)
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2B_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1A_1_ADDR 68
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1A_1_FIXPT 0x0098D227
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1A_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.19391336772058)
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_1A_1_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2A_1_ADDR 69
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2A_1_FIXPT 0xFFC83430
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2A_1_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.43590739824434)
#define MOD_POSTGAIN_PO_PRESENCE_ALG0_STAGE1_NTHORDERDOUBLE3_2A_1_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_BYPASS - Mono Switch Nx1*/
#define MOD_POSTGAIN_PO_BYPASS_COUNT                   2
#define MOD_POSTGAIN_PO_BYPASS_DEVICE                  "IC1"
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 70
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 71
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_POSTGAIN_PO_BYPASS_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PO_VOLUME - Single SW slew vol (adjustable)*/
#define MOD_PO_VOLUME_COUNT                            2
#define MOD_PO_VOLUME_DEVICE                           "IC1"
#define MOD_PO_VOLUME_ALG0_TARGET_ADDR                 72
#define MOD_PO_VOLUME_ALG0_TARGET_FIXPT                0x003D43C0
#define MOD_PO_VOLUME_ALG0_TARGET_VALUE                SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.478630092322639)
#define MOD_PO_VOLUME_ALG0_TARGET_TYPE                 SIGMASTUDIOTYPE_FIXPOINT
#define MOD_PO_VOLUME_ALG0_STEP_ADDR                   73
#define MOD_PO_VOLUME_ALG0_STEP_FIXPT                  0x00000800
#define MOD_PO_VOLUME_ALG0_STEP_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_PO_VOLUME_ALG0_STEP_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

#endif
